### ISSUE TITLE
Unable to Connect to Scanner in Angular Ionic application

### ISSUE THREAD

**Issue by benkirbycodes** [SocketMobile/socketmobile-capturejs#2]
We're attempting to integrate the SocketMobile SDK into an Ionic app using Angular and Capacitor and are as yet unable to connect the scanner to the app.

Details:
- SocketMobile s700 Scanner
- `socketmobile-capturejs` (SDK v1.3.16, tried both CDN and NPM)
- Device: iPhone 13 (OS v15.6.1)
- Tried pairing the scanner in both iOS Application mode and Basic Keyboard mode
- Tried pairing using Socket Mobile companion app

Example Code (using NPM): 

```
import { Capture } from "socketmobile-capturejs";

const appInfo = {
  appId: <appId>,
  developerId: <developerId>,
  appKey: <appKey>,
};

export class Scan {
  private capture;

  constructor() {
    this.capture = new Capture();
    this.open();
  }

  handler(e) {
    console.log(e);
  }

  open() {
    this.capture
      .open(appInfo, this.handler)
      .then((response) => console.log(response))
      .catch((err) => console.error(err));
  }
}
```

Result: 

```
{
  "jsonrpc":"2.0",
  "id":0,
  "error":
  {
    "code":-27,
    "message":"Unable To Open Device"
  }
}
```

Please let me know if I can provide any further details.

Thanks!

**Comment by EricGlaenzer** [comment]
Hi @benkirbycodes, thank you for your interest in our CaptureJS SDK.
This SDK for iOS does require a plugin that integrates the logic for connecting and managing Bluetooth barcode scanner. 
We have implemented such plugin for ReactNative and Flutter, but not yet for Capacitor.
For Android this should work if you have the Socket Mobile Companion installed on your device.

I looked at the Capacitor plugin documentation, it does not seem to be difficult to adapt the plugin we have for ReactNative for Capacitor. 

As you mentioned the scanner can be configured to use the Keyboard (HID) interface, that could get you going while we provide a plugin for Capacitor.

I will check with our JavaScript developer and we will get back to you.
Thanks,
EricG.

**Comment by sellingsolutions** [comment]
@benkirbycodes @EricGlaenzer The error message "Unable To Open Device" really stems from the socketmobile api sending requests over http. Mixed content (mixing https and http in the same app) isn't allowed in any of the major browsers. https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

Here's an example of the socketmobile capture request getting blocked in Safari:
![CleanShot 2022-10-26 at 22 05 46](https://user-images.githubusercontent.com/1778201/198127286-fdbe52ef-6129-4945-a59f-bedeff6133fa.png)

This is the offending line:
https://github.com/SocketMobile/socketmobile-capturejs/blob/6a312bae34cf6c42699cc392d280756f41ff2197/lib/capture.js#L5

Changing it to https isn't enough though, the server also has to listen to https for this to work.

@EricGlaenzer Please advise

**Comment by EricGlaenzer** [comment]
@sellingsolutions Thank you for mentioning this.
I totally understand although on localhost there isn't really a need for a secure connection. We will investigate if we can add a certificate for a secure https.

**Comment by EricGlaenzer** [comment]
BTW changing to HTTPS will require a certificate of course. In theory using `localhost` or `127.0.0.1` are considered as "Potentially Trustworthy".  
Apparently Safari still considers `localhost` or `127.0.0.1` as mixed content. This has been reported in this bug report: https://bugs.webkit.org/show_bug.cgi?id=171934 

@sellingsolutions what OS/Browser version are you using?

**Comment by sellingsolutions** [comment]
@EricGlaenzer I was testing this on iOS 16 using Safari.

**Comment by sellingsolutions** [comment]
@EricGlaenzer Just to be transparent. We've been integrating the socketmobile-capturejs api, as a part of our new release of CommerceOS. CommerceOS is a retail software platform that, amongst others, the biggest store in the world uses for all its operations. We really like the socket-mobile scanner, but we will be forced to integrate with Zebra instead if this bug doesn't get resolved. This bug is a show-stopper for us, please advise.

**Comment by EricGlaenzer** [comment]
@sellingsolutions If you are using iOS then there should not be any issue, because in iOS we don't use this URL. The only way to get it to work on iOS is to use our Rumba web browser app available on App Store: https://apps.apple.com/us/app/rumba-by-socket-mobile/id971935166
